name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add targets
      run: rustup target add thumbv6m-none-eabi
    - name: Build
      run: cargo build --verbose --target thumbv6m-none-eabi --release
